### ISSUE TITLE
Obfuscated & non-functional code

### ISSUE THREAD

**Issue by FR3DHK** [qeeqbox/raven#2]
I like the demo of this project but when using it I have two issues:

1. raven.js is for some reason obfuscated so understanding how it works is near impossible
2. When initializing the map and trying to add data it doesn't appear or function properly

Thank you for any help!

**Comment by giga-a** [comment]
@FR3DHK Thanks for reporting that

It got obfuscated by an old automated system logic. I have an automated system that's responsible for deploying all my code on GitHub.
