### ISSUE TITLE
Problem drawing repeated data on the map view

### ISSUE THREAD

**Issue by albertcp** [qeeqbox/raven#4]
Hello @giga-a !

I was trying to send different data to the map view and I realized that if you repeat the same combination of IP origin country and IP destination country the attack is only drawn the first time.

For example, the following sequence:
 - IP origin: Germany -> IP destination: EEUU : the attack is drawn on the map view
 - IP origin: Germany -> IP destination: France: the attack is drawn on the map view
 - IP origin: China -> IP destination: Germany: the attack is drawn
 - IP origin germany -> IP destination: EEUU : the attack is not drawn
 - IP origin germany -> IP destination: EEUU: the attack is now drawn
 - ...

Is it possible to change this behavior?

Best regards.

**Comment by giga-a** [comment]
@albertcp I will take a look!

**Comment by giga-a** [comment]
@albertcp I pushed a new update, check it out
